server:
  port: 8081
  servlet:
    context-path: /springboot-kafka

spring:
  application:
    name: springboot-kafka

  datasource:
    url: jdbc:postgresql://localhost:5432/kafkadb
    username: root
    password: 12345
    driver-class-name: org.postgresql.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  kafka:
    bootstrap-servers: localhost:9092 # Dirección del broker de Kafka
    producer:
      retries: 5  # Número de reintentos en caso de fallo al enviar un mensaje.
      batch-size: 16384  # Tamaño máximo del lote antes de enviarlo.
      buffer-memory: 33554432  # Memoria máxima utilizada por el buffer del productor.
      linger-ms: 10  # Tiempo en milisegundos antes de enviar un lote de mensajes.
      acks: all  # Se confirma el mensaje en todos los nodos para mayor confiabilidad.
      enable-idempotence: true  # Evita duplicados asegurando la idempotencia.
      key-serializer: org.apache.kafka.common.serialization.StringSerializer  # Serializador para la clave.
      value-serializer: org.apache.kafka.common.serialization.StringSerializer  # Serializador para el valor.

     
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    mappings:
      enabled: true
